# Generated by Django 6.1 on 2026-09-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_remove_user_is_admin_user_role_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='type',
            field=models.CharField(choices=[('regular', 'Обычное'), ('vip', 'VIP'), ('disabled', 'Отключено')], default='regular', max_length=20),
        ),
    ]
